#!/bin/bash

RING=$1
KEY=$2
CWD=`pwd`
TMP="$CWD/live/$RING/secrets/tmp"
SECRETS_DIR="$CWD/live/$RING/secrets"

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
NC='\033[0;0m'
C_BLUE='\e[0;34m'
NC='\033[0;0m'

printUsage() {
    echo "Required environment variables:"
    echo "  PROJECT_ID:     Google Project ID"
    echo ""
    echo "Usage \`xk secrets-fetch [owner] [dev|test|stg|prod]\`"
}
printUsageAndExit() {
    printUsage
    exit
}

exitWithError() {
    echo "$1" 1>&2
    exit 1
}

if [ "$PROJECT_ID" = "" ]; then
    echo -e "${C_RED}No Google Project ID defined!${NC}"
    printUsageAndExit
fi

if [ "$KEY" = "" ]; then
    echo -e "${C_RED}No KeyChain defined!${NC}"
    printUsageAndExit
fi

if [ "$RING" = "" ]; then
    echo -e "${C_RED}No Ring defined!${NC}"
    printUsageAndExit
fi

mkdir -p $SECRETS_DIR/$KEY

echo -e "${C_BLUE}Fetching secrets for $KEY in $RING environment...${NC}"
gsutil -m cp -r gs://$PROJECT_ID-$KEY-secrets/$KEY $SECRETS_DIR/ 2> /dev/null

if [ ! -d "$SECRETS_DIR/$KEY" ]; then
    exitWithError "Failed to copy $SECRETS_DIR/$KEY from GCS!"
fi
FILES=$(find $SECRETS_DIR/$KEY -type f -name "*.enc")
for file in $FILES; do
    echo -e "${C_BLUE}Decrypting ${file##*/}...${NC}"
    gcloud kms decrypt \
    --project=$PROJECT_ID \
    --location=global \
    --keyring=$RING \
    --key=$KEY \
    --ciphertext-file=$file \
    --plaintext-file=${file%.enc}
    rm $file
done

echo -e "${C_GREEN}Finished! The secrets have been decrypted and saved to live/$RING/secrets/$KEY${NC}"
