#!/bin/bash

set -e

RING=${KEYRING_NAME:-"keyring"}
KEY=$1
CWD=`pwd`
TMP="$CWD/live/$ENV/secrets/tmp"
SECRETS_DIR="$CWD/live/$ENV/secrets"

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_BLUE='\e[0;34m'
NC='\033[0;0m'

printUsage() {
    echo "Required environment variables:"
    echo "  TF_VAR_project_id:     Google Project ID"
    
    echo "Optional environment variables:"
    echo "  KEYRING_NAME :         The name of the keyring for the project"
    echo ""
    echo "Usage \`xk secrets-fetch [owner] [ dev | stg | prod ]\`"
}
printUsageAndExit() {
    printUsage
    exit
}

exitWithError() {
    echo "$1" 1>&2
    exit 1
}

cleanup() {
    rm -rf $(find $SECRETS_DIR/$KEY -type f -name "*.enc")
}

trap cleanup EXIT

if [ "$TF_VAR_project_id" = "" ]; then
    echo -e "${C_RED}No Google Project ID defined!${NC}"
    printUsageAndExit
fi

if [ "$KEY" = "" ]; then
    echo -e "${C_RED}No KeyChain defined!${NC}"
    printUsageAndExit
fi

if [ "$RING" = "" ]; then
    echo -e "${C_RED}No Ring defined!${NC}"
    printUsageAndExit
fi

mkdir -p $SECRETS_DIR/$KEY

echo -e "${C_BLUE}Fetching encrypted secrets from gs://$TF_VAR_project_id-$KEY-secrets (will be decrypted by $KEY key in $TF_VAR_project_id project)...${NC}"
gsutil -m rsync -r -d gs://$TF_VAR_project_id-$KEY-secrets $SECRETS_DIR/$KEY 2> /dev/null

if [ ! -d "$SECRETS_DIR/$KEY" ]; then
    exitWithError "Failed to copy $SECRETS_DIR/$KEY from GCS!"
fi
FILES=$(find $SECRETS_DIR/$KEY -type f -name "*.enc")
for file in $FILES; do
    echo -en "${C_BLUE}Decrypting ${file##*/}...${NC}"
    gcloud kms decrypt \
    --project=$TF_VAR_project_id \
    --location=global \
    --keyring=$RING \
    --key=$KEY \
    --ciphertext-file=$file \
    --plaintext-file=${file%.enc}
    rm $file
    echo -e "${C_GREEN} done!${NC}"
done

echo -e "${C_GREEN}Finished! The secrets have been decrypted and saved to live/$RING/secrets/$KEY${NC}"
