#!/bin/bash

set -e

RING=${KEYRING_NAME:-"keyring"}
KEY=$1
CWD=`pwd`
TMP="$CWD/live/$ENV/secrets/tmp"
SECRETS_DIR="$CWD/live/$ENV/secrets"

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_BLUE='\e[0;34m'
NC='\033[0;0m'

printUsage() {
    echo "Required environment variables:"
    echo "  TF_VAR_project_id:     Google Project ID"
    
    echo "Optional environment variables:"
    echo "  KEYRING_NAME:          The name of the keyring for the project"
    echo ""
    echo "Usage \`xk secrets-push [owner] [dev|test|stg|prod]\`"
}
printUsageAndExit() {
    printUsage
    exit
}

exitWithError() {
    echo "$1" 1>&2
    exit 1
}

if [ "$TF_VAR_project_id" = "" ]; then
    echo -e "${C_RED}No Google Project ID defined!${NC}"
    printUsageAndExit
fi

if [ "$KEY" = "" ]; then
    echo -e "${C_RED}No KeyChain defined!${NC}"
    printUsageAndExit
fi

if [ "$RING" = "" ]; then
    echo -e "${C_RED}No Ring defined!${NC}"
    printUsageAndExit
fi

if [ ! -d "$SECRETS_DIR/$KEY" ]; then
    exitWithError "$SECRETS_DIR/$KEY does not exist locally!"
fi

mkdir -p $TMP/$KEY 2> /dev/null

echo -e "${C_BLUE}Updating secrets for $KEY in $ENV environment...${NC}"
cp -r "$SECRETS_DIR/$KEY" $TMP
FILES=$(find $TMP/$KEY -type f -not -name "*.enc")
for file in $FILES; do
    echo -ne "${C_BLUE}Encrypting ${SECRETS_DIR}/${file##*/}...${NC}"
    gcloud kms encrypt \
    --project=$TF_VAR_project_id \
    --location=global \
    --keyring=$RING \
    --key=$KEY \
    --plaintext-file=$file \
    --ciphertext-file=$file.enc
    rm $file
    echo -e "${C_GREEN} done!"
done
gsutil -m rsync -r -d $TMP/$KEY gs://$TF_VAR_project_id-$KEY-secrets 2> /dev/null
rm -r $TMP/$KEY
rmdir $TMP

echo -e "${C_GREEN}Finished! The secrets have been encrypted and saved to \
gs://$TF_VAR_project_id-$KEY-secrets${NC}"
