#!/bin/bash

KEY=$1
RING=$2
CWD=`pwd`
TMP="$CWD/live/$RING/secrets/tmp"
SECRETS_DIR="$CWD/live/$RING/secrets"

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_YLW='\e[0;33m'
NC='\033[0;0m'

printUsage() {
    echo "Required environment variables:"
    echo "  PROJECT_ID:     Google Project ID"
    echo ""
    echo "Usage \`xk secrets-push [owner] [dev|test|stg|prod]\`"
}
printUsageAndExit() {
    printUsage
    exit
}

exitWithError() {
    echo "$1" 1>&2
    exit 1
}

if [ "$PROJECT_ID" = "" ]; then
    echo -e "${C_RED}No Google Project ID defined!${NC}"
    printUsageAndExit
fi

if [ "$KEY" = "" ]; then
    echo -e "${C_RED}No KeyChain defined!${NC}"
    printUsageAndExit
fi

if [ "$RING" = "" ]; then
    echo -e "${C_RED}No Ring defined!${NC}"
    printUsageAndExit
fi

# ---------------------

if [ ! -d "$SECRETS_DIR/$KEY" ]; then
    exitWithError "$SECRETS_DIR/$KEY does not exist locally!"
fi

mkdir -p $TMP/$KEY 2> /dev/null

echo -e "${C_YLW}Updating secrets for $KEY in $RING environment...${NC}"
cp -r "$SECRETS_DIR/$KEY" $TMP
FILES=$(find $TMP/$KEY -type f -not -name "*.enc")
for file in $FILES; do
    echo "Processing file ${file##*/}..."
    gcloud kms encrypt \
    --project=$PROJECT_ID \
    --location=global \
    --keyring=$RING \
    --key=$KEY \
    --plaintext-file=$file \
    --ciphertext-file=$file.enc
    rm $file
done
gsutil -m cp -r $TMP/$KEY/ gs://$PROJECT_ID-$KEY-secrets/ 2> /dev/null
rm -r $TMP/$KEY

echo -e "${C_GREEN}Finished!${NC}"
