#!/bin/bash
set -euo pipefail
cd exekube

# ------------------------------------------------------------------------------
# Set variables and create files
# ------------------------------------------------------------------------------

export XK_LIVE_DIR=$PWD/live/apps-project
export TF_VAR_cloudflare_auth=$(echo -n $TF_VAR_cloudflare_auth | base64 -d)
export HELM_HOME=$PWD/cache/.helm

echo "Restoring cache..."
mkdir -p cache/.terragrunt \
        cache/.kube \
        cache/.helm
cp -a cache/.terragrunt /root
touch cache/.kube/config
cat cache/.kube/config
export KUBECONFIG=$PWD/cache/.kube/config

mkdir -p $PWD/backup/tls
echo $YAML_SECRETS_ENCODED | base64 -d > backup/tls/secret.yaml

echo $GCLOUD_SA_KEY | base64 -d > google-credentials.json
export GOOGLE_CREDENTIALS="$PWD/google-credentials.json"
gcloud auth activate-service-account \
        --key-file=google-credentials.json

# ------------------------------------------------------------------------------
# Run terragrunt / terraform
# ------------------------------------------------------------------------------

# unset KUBECONFIG && ./_docker/docker-entrypoint.sh plan 2>&1 | grep -v 'terragrunt'
./_docker/docker-entrypoint.sh apply 2>&1 | grep -v 'terragrunt'
./_docker/docker-entrypoint.sh destroy 2>&1 | grep -v 'terragrunt'

echo "Saving cache to local directory..."
cp -a /root/.terragrunt ./cache
echo "Done saving cache."
