#!/bin/bash
set -euo pipefail

cd exekube

echo "Restoring cache..."
mkdir -p cache/.terragrunt cache/.kube cache/.helm cache/gcloud /root/.config
cp -a cache/.terragrunt /root
cp -a cache/.kube /root
cp -a cache/.helm /root
cp -a cache/gcloud /root/.config
ls -alh /root/.terragrunt

export XK_LIVE_DIR="$PWD/live/apps-project"
export TF_VAR_cloudflare_auth=$(echo -n $TF_VAR_cloudflare_auth | base64 -d)

mkdir -p $PWD/backup/tls
echo $YAML_SECRETS_ENCODED | base64 -d > $PWD/backup/tls/secret.yaml

echo $GCLOUD_SA_KEY | base64 -d > google-credentials.json
export GOOGLE_CREDENTIALS="$PWD/google-credentials.json"
gcloud auth activate-service-account \
        --key-file=$PWD/google-credentials.json

./_docker/docker-entrypoint.sh plan 2>&1 | grep -v 'terragrunt'

echo "Saving cache to local directory..."

cp -a /root/.terragrunt ./cache
cp -a /root/.helm ./cache
cp -a /root/.kube ./cache
cp -a /root/.config/gcloud ./cache

ls -alh $PWD/cache/.terragrunt
echo "Done saving cache."
