#!/bin/bash

set -e

gcloud projects get-iam-policy $TF_VAR_project_id > $TF_VAR_project_id.iam.policy.yml

cat <<EOF >> $TF_VAR_project_id.iam.policy.yml
auditConfigs:
- auditLogConfigs:
  - logType: DATA_WRITE
  - logType: DATA_READ
  service: storage.googleapis.com
- auditLogConfigs:
  - logType: DATA_WRITE
  - logType: DATA_READ
  service: cloudkms.googleapis.com
EOF

gcloud projects set-iam-policy $TF_VAR_project_id $TF_VAR_project_id.iam.policy.yml

rm $TF_VAR_project_id.iam.policy.yml
