apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rails-app.fullname" . }}
  labels:
    app: {{ template "rails-app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "rails-app.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec: # PodSpec
      containers:
        - name: {{ template "rails-app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.image.pullPolicy }}
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: "yes"
            - name: RAILS_LOG_TO_STDOUT
              value: "yes"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.fullname" . }}
                  key: secret-key-base
            - name: POSTGRES_HOST
              value: {{ template "rails-app.postgresql.fullname" . }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.fullname" . }}
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.fullname" . }}
                  key: db-password
          ports:
            - containerPort: {{ .Values.servicePort | int }}
          workingDir: /app
          command: ["bash", "-c"]
          args: ["rails db:setup db:migrate && bundle exec puma -C config/puma.rb"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
